apiVersion: v1
kind: Service
metadata:
  name: nodeportservice
spec:
  type: NodePort
  selector:
      type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
